### ISSUE TITLE
Patterns FKey

### ISSUE THREAD

**Issue by travisallen6** [travisallen6/shift-tango#1]
Error: insert or update on table "patterns" violates foreign key constraint "patterns_emp_id_fkey"
controller.js:28
code:"23503"
column:undefined
constraint:"patterns_emp_id_fkey"
dataType:undefined
detail:"Key (emp_id)=(123456) is not present in table "users"."
file:"ri_triggers.c"
hint:undefined
internalPosition:undefined
internalQuery:undefined
length:256
line:"3266"
message:"insert or update on table "patterns" violates foreign key constraint "patterns_emp_id_fkey""
name:"error"
position:undefined
routine:"ri_ReportViolation"
schema:"public"
severity:"ERROR"
stack:"error: insert or update on table "patterns" violates foreign key constraint "patterns_emp_id_fkey"\n    at Connection.parseE (c:\Users\Travis\Dropbox\DevMountain\Projects\War-Panda\war-panda\node_modules\pg\lib\connection.js:545:11)\n    at Connection.parseMessage (c:\Users\Travis\Dropbox\DevMountain\Projects\War-Panda\war-panda\node_modules\pg\lib\connection.js:370:19)\n    at TLSSocket.<anonymous> (c:\Users\Travis\Dropbox\DevMountain\Projects\War-Panda\war-panda\node_modules\pg\lib\connection.js:113:22)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at TLSSocket.Readable.push (_stream_readable.js:208:10)\n    at TLSWrap.onread (net.js:594:20)"
table:"patterns"
where:undefined
__proto__:Object {constructor: , name: "Error", message: "", …}

**Comment by travisallen6** [comment]
Modified table constraint. Closing issue.
